name: Build and push images to registry

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      no_cache:
        description: 'Force a rebuild of the Docker images without using cache.'
        required: false
        type: boolean
        default: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PUSH_IMAGE: ${{ github.event_name != 'pull_request' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        if: env.PUSH_IMAGE == 'true'
        uses: docker/login-action@v4.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Global SemVer Metadata
        id: meta
        uses: docker/metadata-action@v6.1.0
        with:
          images: ${{ env.REGISTRY }}/mardi4nfdi/wikibase
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.1.0

      - name: Build and Push All Images via Bake
        uses: docker/bake-action@v7.2.0
        with:
          files: docker-bake.hcl
          push: ${{ env.PUSH_IMAGE }}
          load: ${{ env.PUSH_IMAGE == 'false' }}
          no-cache: ${{ github.event.inputs.no_cache || false }}
          set: |
            *.cache-from=type=gha,scope=wikibase-shared
            *.cache-to=type=gha,mode=max,scope=wikibase-shared
        env:
          B_TAGS: ${{ steps.meta.outputs.json }}
